BUG: memleak part 3 (CFFI only)
darshan-hpc/darshan pull request #819
Opened 2022-09-22 21:44 UTC by tylerjereddy

* this should be reviewed after gh-816, and fixes
    the residual memory leak there so that we get
    a flat memory profile with repeated calls
    to `log_get_generic_record()`; after rebasing, this PR
   should simplify to a few CFFI backend changes to free
   `buf[0]` in a few places and make explicit copies for NumPy
    where it is pointing to the dropped memory buffer
    
 * note that `RUNTIME` heatmap doesn't seem to like
    the extra `free()`, it causes some testing issues,
    so I've excluded that here--hopefully that module
    just doesn't have the same problem..

Gradual mem spike -> flat profile:

![image](https://user-images.githubusercontent.com/7903078/191856812-1a3f7d94-8b41-456a-9344-c74ab10f75a1.png)

2022-09-23 16:48 UTC, shanedsnyder requested changes

2022-09-23 16:48 UTC, shanedsnyder commented on darshan-util/pydarshan/darshan/backend/cffi_backend.py
> +        libdutil.darshan_free(buf[0])
Probably not super obvious from the code, but `darshan_log_get_record` will not return with any data malloced if `r < 1` (i.e., there's no more data or an error was encountered). I think we need to drop this `free()`. I started to wonder why you didn't see double free errors for this, but realized on this code path the output pointer is set to `NULL`, so you are just freeing a `NULL` pointer which isn't technically illegal.

2022-09-23 16:48 UTC, shanedsnyder commented on darshan-util/pydarshan/darshan/backend/cffi_backend.py
> +        libdutil.darshan_free(buf[0])
Drop this `free()` as well.

2022-09-23 16:48 UTC, shanedsnyder commented on darshan-util/pydarshan/darshan/backend/cffi_backend.py
> +        libdutil.darshan_free(buf[0])
Drop this `free()` as well.

2022-09-23 16:53 UTC, shanedsnyder commented
>note that RUNTIME heatmap doesn't seem to like
the extra free(), it causes some testing issues,
so I've excluded that here--hopefully that module
just doesn't have the same problem..

I'll see if I can figure out what's going on here, that seems like it could be a problem

2022-09-23 17:48 UTC, tylerjereddy commented
Ok, I think I addressed the comments so far. I also rebased to vastly simplify the displayed diff.

2022-09-27 17:27 UTC, shanedsnyder commented
> > note that RUNTIME heatmap doesn't seem to like
> > the extra free(), it causes some testing issues,
> > so I've excluded that here--hopefully that module
> > just doesn't have the same problem..
> 
> I'll see if I can figure out what's going on here, that seems like it could be a problem

I think I fixed the memory leak and the test errors via [b21d644](https://github.com/darshan-hpc/darshan/pull/819/commits/b21d644024ed813c62b6130df692ad2c4d9f04cf), which looked like they were ultimately caused by incorrect data being stored in heatmap records when we add in the necessary `free()` statement to avoid mem leaks. Looks like we just needed a `np.copy()` as in other places (e.g., DXT segment extraction) so record data isn't freed out from under heatmap records.

@tylerjereddy if it looks good to you, I think we can go ahead and merge. I'm not sure if we had a good reproducer for the heatmap module-specific memory leak, but might be good to confirm this is working as expected in terms of leaking if we do.

2022-09-27 17:39 UTC, tylerjereddy commented
@shanedsnyder Probably not HEATMAP reproducer yet, but may we can include that separately as part of https://github.com/darshan-hpc/darshan/issues/817. I'd probably just lift the reproducers from gh-811, and supplement for any modules not covered there, if needed. I guess that means putting stuff in the `asv` suite, which takes a bit more testing.

Once this is merged (it looks sensible to me as well) maybe we should ping in gh-811 for user confirmation of the fix if they are comfortable recompiling from `main`.

2022-09-27 17:51 UTC, shanedsnyder approved these changes

2022-09-27 17:52 UTC, merged